config/routes.rb
Demo::Application.routes.draw do
  get "say/hello"

  get "say/goodbye"
  
  resources :events
  resources :targets

end

app/models/category.rb
class Category < ActiveRecord::Base
  has_many :targets
end

app/models/event.rb
class Event < ActiveRecord::Base
  validates_presence_of :name
end

app/models/metadata.rb
class Metadata < ActiveRecord::Base
  self.table_name = "metadata"
  
  has_many :target
end

app/models/target.rb
class Target < ActiveRecord::Base
  belongs_to :category
  belongs_to :metadata
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :target
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  
  before_filter :find_event, :only => [ :show, :edit, :update, :destroy]
  
  def index
    @events = Event.page(params[:page]).per(5)
    
    respond_to do |format|
      format.html
      format.xml { render :xml => @events.to_xml }
      format.json { render :json => @events.to_json }
      format.atom { @feed_title = "My event list" } # index.atom.builder
    end
  end
  
  def new
    @event = Event.new
  end
  
  def create
    @event = Event.new(params[:event])
    if @event.save
      flash[:notice] = "event was successfully created"
      redirect_to events_url
    else
      render :action => :new
    end
    
    
  end
  
  def show
    respond_to do |format|
      format.html
      format.xml { render :xml => @event.to_xml }
      format.json { render :json => @event.to_json }
    end
  end
  
  def edit
    
  end
  
  def update
    if @event.update_attributes(params[:event])
      
      flash[:notice] = "event was successfully updated"
      redirect_to event_url(@event)
    else
      render :action => :edit
    end
    
    
  end
  
  def destroy
    @event.destroy
    
    flash[:alert] = "event was successfully deleted"

    redirect_to events_url
  end
  
  protected

  def find_event
    @event = Event.find(params[:id])
  end
end

app/controllers/say_controller.rb
class SayController < ApplicationController
  def hello
    @time = Time.now
    @files = Dir.glob('*')
  end

  def goodbye
  end

end

app/controllers/targets_controller.rb
class TargetsController < ApplicationController
  
  def index 
    @targets = Target.all
    
  end
  
  def new
    @target = Target.new(:category => Category.find(1), :metadata => Metadata.find(1), :user_id => User.find(1), :status => "active")
    
  end
  
  def create
    @target = Target.new(params[:target])
    @last = Target.order("id desc").where("user_id = ?", 1).first
    
    if(@last != nil && @last.sequence_no != nil)
      @target.sequence_no = @last.sequence_no + 1
    else
      @target.sequence_no = 1
    end
    
    if @target.save
      redirect_to targets_url
    else
      render :action => :new
    end
    
  end
  
  def destroy
    @target.destroy

    redirect_to targets_url
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/event_helper.rb
module EventHelper
end

app/helpers/say_helper.rb
module SayHelper
end

app/helpers/sike_users_helper.rb
module SikeUsersHelper
end

app/helpers/targets_helper.rb
module TargetsHelper
end

app/views/events/_form.html.erb
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>

app/views/events/edit.html.erb
<%= form_for @event, :url => event_path(@event), :html => { :method => :put } do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    
    <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <li>
    <%= link_to event.name, event_path(event) %>
    <%= link_to 'edit', edit_event_path(event) %>
    <%= link_to 'delete', event_path(event), :method => :delete %>
  </li>
<% end %>
</ul>
<%= paginate @events %>
 
<%= link_to 'new event', new_event_path %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
    <%= render :partial => 'form', :locals => { :f => f } %>
    
    <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= @event.description %>
 
<p><%= link_to 'back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<meta content="text/html; charset=utf-8" http-equiv="Content-Type" />
	<title>啄米</title>
	<meta content="啄米网" name="keywords" />
	<meta content="啄米网" name="description" />

	<link type="image/x-icon" rel="Shortcut Icon" href="favicon.ico" />
	<link type="image/x-icon" rel="Bookmark" href="favicon.ico" />
  <%= stylesheet_link_tag :zhuomi %>
  <%= javascript_include_tag :zhuomi %>
  <%= csrf_meta_tag %>
</head>
<body>
	<div id="header">
	        <div class="pw align-c cf">
	            <div class="col-l nohand">
	                <h1 class="col-l">
	                    <a href="#this" id="logo" class="col-l">
	                        <img src="../images/high/logo.png" alt="啄米" />
	                    </a>
	                </h1>
	                <div id="" class="col-l ml-5">
	                    <p class="yel txt-m">Beta</p>
	                    <p class="whi txt-m mt-1">收集，分类和交流你的日常数据</p>
	                </div>
	            </div>
	            <div id="accountbox" class="col-r cf">
	                <div class="ab-profile col-l">
	                    <a class="ab-headshot col-l" href="reg.htm">
	                        <img src="../images/photos/s.jpg" alt="LiangShu" title="LiangShu" />
	                    </a>
	                    <span class="ab-name col-l ml-5">Shu</span>
	                </div>
	                <a href="#this" class="ab-drop col-l ml-8"></a>
	            </div>
	        </div>
	    </div>
	    <p class="shoulder"></p>
	    <div id="wrapper" class="pw align-c">
<%= yield %>
</div>
    <div id="footer" class="pw align-c">
        <p class="col-r">
            天才，都TM是练出来的
            <a href="#this" class="bookmark bkmk-sina" title="Sina"></a>
        </p>
        <div id="aboutus" class="cf">
            <div class="col-l">
                <p class="col-l">沪ICP备05054668号 Copyright &copy; 2011 啄米科技</p>
                <ul class="au-links col-l hor">
                    <li>-</li>
                    <li>
                        <a href="#">关于啄米</a>
                    </li>
                    <li>
                        <a href="#">关于我们</a>
                    </li>
                </ul>
            </div>
            <div class="col-l ml-5">
                <a href="#this" id="au-prev" class="hidden"></a>
                <a href="#this" id="au-next"></a>
            </div>
        </div>
    </div>


</body>
</html>

app/views/say/goodbye.html.erb
<h1>Say#goodbye</h1>
<p>Find me in app/views/say/goodbye.html.erb</p>

app/views/say/hello.html.erb
<h1>Hello from Rails!</h1>
<p>It's time <%= @time %></p>
<p>Time to say
	<%= link_to "Good Bye!", say_goodbye_path %>
	
	<% for file in @files%>
		file is <%= file %>
	<% end %>
</p>

app/views/targets/index.html.erb
<% @targets.each do |target| %>
  <li>
    <%= link_to target.target_count, target_path(target) %>
    <%= link_to 'delete', target_path(target), :method => :delete %>
  </li>
<% end %>
</ul>
 
<%= link_to 'new target', new_target_path %>

app/views/targets/new.html.erb
<script language="JavaScript" type="text/javascript"> 
    // <![CDATA[
	function setValue(v){ 
		jQuery("#target_target_count").val(v);
	}
	
	function submitForm(){
		document.forms[0].submit();
	}
	
	// ]]>
	    </script>
<div class="pg-title">
            <span class="col-r txt-6xl pg-title-welcome">欢迎来到啄米...</span>
            <h2 class="txt-4xl azure">
                制定个人计划
            </h2>
        </div>
        <div id="main" class="mt-20 cf">
            <div class="col-l col-w">
                <div id="profileview" class="cf">
                    <a href="#this" class="pv-headshot col-l">
                        <img src="../images/photos/xl.jpg" alt="更改头像" title="LiangShu" />
                    </a>
                    <div class="col-l ml-25">
                        <strong class="azure">Shu</strong>
                        <p class="mt-5">
                            <span class="gra">为了提供更好的服务，建议在之后的个人页面中完善</span>
                            <a href="#this" class="azure">个人资料</a>
                        </p>
                    </div>
                </div>
                <div class="clear mt-15">
                    <p class="txt-8xl">
                        我要跑步
                        <span id="planhour-txt" class="txt-5xl azure">1</span>
                        <span class="gra">小时</span>
                    </p>
                    <div id="planhour" class="mt-25">
                        <a href="#this" class="ph-one" onclick="setValue(1);">
                            <span class="ph-txt"><span class="ph-val">1</span><span class="ph-unit">小时</span></span>
                        </a>
                        <a href="#this" class="ph-ten" onclick="setValue(10);">
                            <span class="ph-txt"><span class="ph-val">10</span><span class="ph-unit">小时</span></span>
                        </a>
                        <a href="#this" class="ph-hdrd" onclick="setValue(100);">
                            <span class="ph-txt"><span class="ph-val">100</span><span class="ph-unit">小时</span></span>
                        </a>
                    </div>
                    <p class="txt-4xl bla mt-20">真的准备好了？</p>
					<%= form_for @target, :url => targets_path do |f| %>
						<%= f.hidden_field :target_count %>
						<%= f.hidden_field :category_id %>
						<%= f.hidden_field :metadata_id %>
						<%= f.hidden_field :user_id %>
						<%= f.hidden_field :status %>
						<br />
                    <p class="mt-18">
                        <a href="#this" class="btn-start outerglow" onclick="submitForm();">
                            立刻行动
                            <span class="icon-go"></span>
                        </a>
                    </p>	
					<% end %>
                </div>
            </div>
            <div class="col-l col-n">
            
            </div>
        </div>